blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'
urlpatterns = [
    path('', views.home, name='home'),
    path('articles/', views.articles, name='articles'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('resume/', views.resume, name='resume'),
    path('articles/<int:pk>', views.ArticleDetailView.as_view(), name='article_detail'),
    path('article_create/', views.article_create, name='article_create'),
    path('article_delete/<int:article_id>', views.article_delete, name='article_delete'),
    path('article_update/<int:article_id>', views.article_update, name='article_update'),
]

jovychat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('userprofile/', include('userprofile.urls')),
    path('password-reset/', include('password_reset.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.urls import path
from . import views


app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<user_id>', views.user_delete, name='delete'),
]

templates/password_reset/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>JovyChat</title>
    {% block css %}
        <link rel="stylesheet" href="{% static '../../static/blog/bootstrap/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static '../../static/blog/main.css' %}">
        <link rel="stylesheet" href="{% static '../../static/blog/md_css/monokai.css' %}">
    {% endblock %}

</head>
<body>
<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-light bg-light">
        <a class="navbar-brand" href="#">JovyChat</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-center" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link" href="{% url 'blog:home' %}">Home</a>
                <a class="nav-item nav-link" href="{% url 'blog:articles' %}">Articles</a>
                <a class="nav-item nav-link" href="{% url 'blog:about' %}">About</a>
                <a class="nav-item nav-link" href="{% url 'blog:resume' %}">Resume</a>

            </div>
        </div>
    </nav>
</header>

<main role="main" class="container">

    <div class="row">
        <div class="col-md-9">
            {% block content %}
            {% endblock %}
        </div>
        <div class="col-md-3">
            <div class="content-section">
                {% if user.is_authenticated %}
                    <h4>{{ user.username }}</h4>
                    <p class="text-muted">bios.</p>
                    <div class="list-group">
                        <a href="{% url 'userprofile:logout' %}" class="list-group-item list-group-item-light">
                            <small>Logout</small>
                        </a>
                        <a href="{% url 'blog:article_create' %}" class="list-group-item list-group-item-light">
                            <small>Create New</small>
                        </a>
                        <a href="#" class="list-group-item list-group-item-light" onclick="user_delete()">
                            <small>Delete Acount</small>
                        </a>
                    </div>
                {% else %}
                    <h4>Anonymous</h4>
                    <p class="text-muted">No comment.</p>
                    <div class="list-group">
                        <a href="{% url 'userprofile:login' %}" class="list-group-item list-group-item-light"><small>Login</small></a>
                        <a href="{% url 'userprofile:register' %}" class="list-group-item list-group-item-light"><small>Register</small></a>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</main>
<script src="{% static '../../static/blog/js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static '../../static/blog/js/popper.min.js' %}"></script>
<script src="{% static '../../static/blog/bootstrap/bootstrap.min.js' %}"></script>
<script src="{% static '../../static/blog/layer/layer.js' %}"></script>

{% if user.is_authenticated %}
    <form
            style="display: none"
            action="{% url 'userprofile:delete' user_id=user.id%}"
            id="user_delete"
            method="POST">
    {% csrf_token %}
        <input type="submit" value="Send delete">
    </form>
    <script>
        function user_delete() {
            layer.open({
                title: 'Confirm to delete',
                content: 'Ensure to delete this user account?',
                yes: function (index, layer) {
                    $('form#user_delete input').click();
                    layer.close(index);
                },
            })
        }
    </script>
{% endif %}

</body>
</html>