blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'
urlpatterns = [
    path('', views.home, name='home'),
    path('articles/', views.articles, name='articles'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('resume/', views.resume, name='resume'),
    path('articles/<int:pk>', views.ArticleDetailView.as_view(), name='article_detail'),
    path('article_create/', views.article_create, name='article_create'),
    path('article_delete/<int:article_id>', views.article_delete, name='article_delete'),
    path('article_update/<int:article_id>', views.article_update, name='article_update'),
]

jovychat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('userprofile/', include('userprofile.urls')),
    path('password-reset/', include('password_reset.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.urls import path
from . import views


app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<user_id>', views.user_delete, name='delete'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.utils.html import strip_tags
from taggit.managers import TaggableManager
from PIL import Image
import markdown


class ArticleSection(models.Model):
    title = models.CharField(max_length=25, blank=True)
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


class Article(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=50)
    pub_date = models.DateTimeField(auto_now_add=True)
    # modify_date = models.DateTimeField(auto_now=True)
    content = models.TextField()
    total_views = models.PositiveIntegerField(default=0)
    brief = models.TextField(blank=True)
    tags = TaggableManager(blank=True)
    avatar = models.ImageField(upload_to='article/%Y/%m%d/', default='article/default.jpg')
    section = models.ForeignKey(
        ArticleSection,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='article'
    )

    class Meta:
        verbose_name = 'article'
        verbose_name_plural = 'articles'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        article = super(Article, self).save(*args, **kwargs)
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
        ])
        self.brief = strip_tags(md.convert(self.content))[:10]
        if self.avatar and not kwargs.get('update_fields'):
            image = Image.open(self.avatar)
            (x, y) = image.size
            new_x = 256
            new_y = int(new_x * (y / x))
            resized_image = image.resize((new_x, new_y), Image.ANTIALIAS)
            resized_image.save(self.avatar.path)
        return article

blog/forms.py
from django import forms
from .models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ('title', 'content', 'tags', 'avatar', 'brief')

blog/views.py
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect
import datetime
from .models import Article, ArticleSection
import markdown
from .forms import ArticleForm
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView, DetailView, DeleteView
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy

def home(request):
    articles = Article.objects.all()
    context = {
        'articles': articles
    }
    return render(request, 'blog/home.html', context=context)


def articles(request):
    search = request.GET.get('search')
    order = request.GET.get('order')
    tag = request.GET.get('tag')
    section = request.GET.get('section')
    # initial query set
    article_list = Article.objects.all()

    if search:
        if order == 'total_views':
            article_list = Article.objects.filter(
                Q(title__icontains=search) |
                Q(content__icontains=search)
            ).order_by('-total_views')
        else:
            article_list = Article.objects.filter(
                Q(title__icontains=search) |
                Q(content__icontains=search)
            )
    else:
        search = ''
        if order == 'total_views':
            article_list = Article.objects.all().order_by('-total_views')
        else:
            article_list = Article.objects.all().order_by('-pub_date')

    # tag query:
    if tag and tag != 'None':
        article_list = article_list.filter(tags__name__in=[tag])

    # section query:
    if section is not None and section.isdigit():
        article_list = article_list.filter(section=section)

    paginator = Paginator(article_list, 4)
    page = request.GET.get('page')
    articles = paginator.get_page(page)
    context = {
        'articles': articles,
        'order': order,
        'search': search,
        'tag': tag,
    }
    return render(request, 'blog/articles.html', context=context)


class AboutView(TemplateView):
    template_name = 'blog/about.html'


def resume(request):
    try:
        article = Article.objects.get(title='Resume')
        article.content = markdown.markdown(article.content,
                                            extensions=[
                                                # 包含 缩写、表格等常用扩展
                                                'markdown.extensions.extra',
                                                # 语法高亮扩展
                                                'markdown.extensions.codehilite',
                                            ])
        context = {
            'article': article
        }
        return render(request, 'blog/resume.html', context=context)
    except ObjectDoesNotExist as e:
        return HttpResponse(e)


class ArticleDetailView(DetailView):
    model = Article
    template_name = 'blog/article_detail.html'
    context_object_name = 'article'
    md = markdown.Markdown(
        extensions=[
            # 包含 缩写、表格等常用扩展
            'markdown.extensions.extra',
            # 语法高亮扩展
            'markdown.extensions.codehilite',
            # 目录拓展 Table of Contents
            'markdown.extensions.toc'
        ])

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        self.object.total_views += 1
        self.object.save()
        return response

    def get_object(self, md=md, queryset=None):
        article = super().get_object(queryset=None)
        article.content = md.convert(article.content)
        return article

    def get_context_data(self, md=md, **kwargs):
        context = super().get_context_data(**kwargs)
        toc = md.toc
        context['toc'] = toc
        return context


@login_required(login_url='userprofile:login')
def article_create(request):
    if request.method == 'POST':
        article_post_form = ArticleForm(request.POST, request.FILES)
        if article_post_form.is_valid():
            new_article = article_post_form.save(commit=False)
            if request.POST['section'] != 'none':
                new_article.section = ArticleSection.objects.get(id=request.POST['section'])
            new_article.save()
            article_post_form.save_m2m()
            return redirect('blog:articles')
        else:
            return HttpResponse("提交有误，请重新提交。")
    else:
        article_post_form = ArticleForm()
        sections = ArticleSection.objects.all()
        context = {
            'article_post_form': article_post_form,
            'sections': sections
        }
        return render(request, 'blog/article_create.html', context=context)


@login_required(login_url='userprofile:login')
def article_delete(request, article_id):
    article_to_delete = Article.objects.get(id=article_id)
    article_to_delete.delete()
    return redirect('blog:articles')


@login_required(login_url='userprofile:login')
def article_update(request, article_id):
    article_to_update = Article.objects.get(id=article_id)
    if request.method == 'POST':
        article_post_form = ArticleForm(data=request.POST, instance=article_to_update)
        if article_post_form.is_valid():
            article_post_form.save(commit=False)
            if request.POST['section'] != 'none':
                article_to_update.section = ArticleSection.objects.get(id=request.POST['section'])
            article_to_update.save()
            article_post_form.save_m2m()
            return redirect('blog:article_detail', article_id=article_to_update.id)
        else:
            return HttpResponse("Update error.")
    else:
        sections = ArticleSection.objects.all()
        context = {
            'article': article_to_update,
            'sections': sections
        }
        return render(request, 'blog/article_update.html', context=context)

templates/blog/about.html
{% extends 'blog/base.html' %}
{% block content %}

    <section class="section is-large">
        <div class="container">
            <h1 class="title has-text-centered">About</h1>
            <h2 class="subtitle has-text-centered">
                A simple container to divide your page into <strong>sections</strong>, like the one you're currently
                reading
            </h2>
        </div>
    </section>

{% endblock %}

templates/blog/article_create.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="columns is-centered">
        <div class="column is-three-fifths-desktop is-full-touch">
            <div class="box is-transparent">
                <form method="POST" action="." enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="field">
                        <label class="label" for="tags">标题:</label>
                        <input type="text" class="control input col-3" id="title" name="title">
                    </div>

                    <div class="field">
                        <label class="label" for="tags">标签:</label>
                        <input type="text" class="control input col-3" id="tags" name="tags">
                    </div>

                    <div class="field">
                        <div class="control">
                            <label class="label">选择文章分类:</label>
                            <div class="select">
                                <select name="section" id="section">
                                    {% for section in sections %}
                                        <option value="{{ section.id }}">{{ section }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="field">
                        <div id="file-js" class="file has-name">
                            <label class="file-label">
                                <input class="file-input" type="file" name="avatar">
                                <span class="file-cta">
                                <span class="file-icon"><i class="fas fa-upload"></i></span>
                                <span class="file-label">请选择图片文件上传</span>
                                </span>
                                <span class="file-name">No file uploaded</span>
                            </label>
                        </div>
                    </div>

                    <div class="field">
                        <div class="control is-medium is-info is-loading">
                            <label class="label" for="content">文章概述</label>
                            <textarea name="brief" id="brief" class="textarea" placeholder="Input article's brief"
                                      rows="5"></textarea>
                        </div>
                    </div>
                    <div class="field">
                        <div class="control is-medium is-info is-loading">
                            <label class="label" for="content">正文内容(Markdown格式)</label>
                            <textarea name="content" id="content" class="textarea" placeholder="Input markdown here"
                                      rows="15"></textarea>
                        </div>
                    </div>
                    <div class="field has-text-centered">
                        <button class="button is-success is-large" type="submit">提交</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- get uploaded file name -->
    <script>
        const fileInput = document.querySelector('#file-js input[type=file]');
        fileInput.onchange = () => {
            if (fileInput.files.length > 0) {
                const fileName = document.querySelector('#file-js .file-name');
                fileName.textContent = fileInput.files[0].name;
            }
        }
    </script>
{% endblock %}

templates/blog/article_detail.html
{% extends 'blog/base.html' %}
{% load static %}


{% block content %}
    <!-- article start -->
    <div class="container">
        <section class="articles columns">
            <!-- set table of content -->
            <div class="column is-one-fifth is-hidden-mobile">
                <div class="box toc is-radiusless">
                    <h6 class="title has-text-centered"><strong>目录</strong></h6>
                    <hr>
                    <div>
                        {{ toc|safe }}
                    </div>
                </div>
            </div>
            <!-- end table of content -->

            <!-- set article detail -->
            <div class="column is-three-fifths-desktop is-full-touch">
                <div class="card article">
                    <div class="card-content">

                        <div class="media">
                            <div class="media-center">
                                <img src="{% static 'blog/images/test.jpg' %}"
                                     class="author-image" alt="Placeholder image">
                            </div>

                            <div class="media-content has-text-centered">
                                <p class="title article-title">{{ article.title }}</p>

                                <!-- set tags -->
                                <div class="tags level-item has-addons-centered">
                                    {% for tag in article.tags.all %}
                                        <span class="tag is-small has-text-white-bis is-link">#{{ tag }}</span>
                                    {% endfor %}
                                </div>
                                <!-- end set tags -->

                                <div class="tags has-addons level-item">
                                    <span class="tag is-rounded is-warning has-text-weight-bold">
                                        <i class="fa fa-eye"></i>&nbsp;
                                        {{ article.total_views }}
                                    </span>
                                    <span class="tag is-rounded">{{ article.pub_date|date:'Y-m-d' }}</span>
                                    {% if user.is_authenticated %}
                                        <a class="tag is-rounded is-small is-danger" href="#"
                                           onclick="confirm_safe_delete()">·<small>删除文章</small></a>
                                        <a class="tag is-small is-info"
                                           href="{% url "blog:article_update" article_id=article.id %}">·<small>编辑文章</small></a>
                                    {% else %}
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="content article-body">
                            {{ article.content|safe }}
                        </div>
                    </div>
                </div>
            </div>
            <!-- end set article detail -->

        </section>
        <!-- article end -->
        <!-- csrf hidden form -->
        <form style="display:none;"
              id="safe_delete"
              action="{% url 'blog:article_delete' article_id=article.id %}"
              method="POST">
            {% csrf_token %}
            <button type="submit">Delete</button>
        </form>
        <!-- csrf hidden form end -->
    </div>
{% endblock %}

templates/blog/article_update.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="columns is-centered">
        <div class="column is-three-fifths-desktop is-full-touch">
            <div class="box is-transparent">
                <form method="POST" action="{% url "blog:article_update" article_id=article.id %}"
                      enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="field">
                        <label class="label" for="tags">标题:</label>
                        <input type="text" class="control input col-3" id="title" name="title"
                               value="{{ article.title }}">
                    </div>

                    <div class="field">
                        <label class="label" for="tags">标签:</label>
                        <input type="text" class="control input col-3" id="tags" name="tags">
                        <hr>
                        {% for tag in article.tags.all %}
                            <div class="tags has-addons">
                                <span class="tag is-rounded is-primary">#{{ tag }}</span>
                                <span class="tag is-delete"></span>
                            </div>
                        {% empty %}
                        {% endfor %}
                    </div>


                    <div class="field">
                        <div class="control">
                            <label class="label">选择文章分类:</label>
                            <div class="select">
                                <select name="section" id="section">
                                    {% for section in sections %}
                                        <option value="{{ section.id }}">{{ section }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="field">
                        <div id="file-js" class="file has-name">
                            <label class="file-label">
                                <input class="file-input" type="file" name="avatar">
                                <span class="file-cta">
                                <span class="file-icon"><i class="fas fa-upload"></i></span>
                                <span class="file-label">请选择图片文件上传</span>
                                </span>
                                <span class="file-name">No file uploaded</span>
                            </label>
                        </div>
                    </div>

                    <div class="field">
                        <div class="control is-medium is-info is-loading">
                            <label class="label" for="brief">文章概述</label>
                            <textarea name="brief" id="brief" class="textarea" rows="5">{{ article.brief }}</textarea>
                        </div>
                    </div>
                    <div class="field">
                        <div class="control is-medium is-info is-loading">
                            <label class="label" for="content">正文内容(Markdown格式)</label>
                            <textarea name="content" id="content" class="textarea" rows="15" >{{ article.content }}</textarea>
                        </div>
                    </div>
                    <div class="field has-text-centered">
                        <button class="button is-success is-large" type="submit">提交</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="zh">
<!-- refer static files -->
<head>
    <meta charset="UTF-8">
    <title>JovyChat</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- import css -->
    {% block css %}
        <link href="https://cdn.bootcss.com/font-awesome/5.11.2/css/all.css" rel="stylesheet">
        <link href="https://cdn.bootcss.com/layer/2.3/skin/layer.css" rel="stylesheet">
        <link href="https://cdn.bootcss.com/animate.css/3.7.2/animate.css" rel="stylesheet">
        <link href="https://cdn.bootcss.com/bulma/0.7.5/css/bulma.css" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'blog/css/article_detail.css' %}">
        <link rel="stylesheet" href="{% static 'blog/css/main.css' %}">
        <link rel="stylesheet" href="{% static 'blog/css/styles.css' %}">
    {% endblock %}
</head>

<body>
<!-- header here -->
{% block header %}
    {% include 'blog/header.html' %}
{% endblock %}
<!-- main content here -->
{% block content %}
{% endblock %}


<!-- footer here -->
{% block footer %}
    {% include 'blog/footer.html' %}
{% endblock %}

<!-- import js -->
{% block js %}
    <script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.js"></script>
    <script src="https://cdn.bootcss.com/popper.js/1.15.0/esm/popper.js"></script>
    <script src="https://cdn.bootcss.com/layer/2.3/layer.js"></script>
    <script src="{% static 'blog/js/main.js' %}"></script>
{% endblock %}
</body>
</html>

templates/blog/footer.html
<footer class="footer is-size-5">
    <div class="container content has-text-centered is-fixed-bottom">
        <p class="has-text-black-bis">
            <strong>JovyChat</strong> Designed by <a href="{% url 'blog:about' %}">Jovy</a>
            Powered by <a href="https://www.djangoproject.com/">Django</a> & <a href="https://bulma.io/">Bulma</a>
        </p>
        <p>
            <strong>Github</strong>:
            <i class="fab fa-github"></i>

            <a href="https://github.com/PJovy">
                https://github.com/PJovy
                <i class="fa fa-star"></i>
            </a>.
        </p>
    </div>
</footer>

templates/blog/header.html
<header>

    <section class="hero is-medium is-black">
        <!-- hero head -->
        <div class="hero-head ">
            <nav class="navbar is-transparent">
                <div class="container">
                    <div class="navbar-brand">
                        <a class="navbar-item" href="{% url 'blog:home' %}">
                            <i class="fas fa-home"></i>
                        </a>
                        <a class="navbar-burger burger" data-target="navbarPrimary" role="button"
                           aria-label="menu" aria-expanded="false">
                            <span aria-hidden="true"></span>
                            <span aria-hidden="true"></span>
                            <span aria-hidden="true"></span>
                        </a>
                    </div>


                    <div id="navbarPrimary" class="navbar-menu">
                        <!-- left side -->
{#                        <div class="navbar-end">#}
{#                            <a class="navbar-item" href="{% url 'blog:home' %}">#}
{#                                主页#}
{#                            </a>#}
{#                            <a class="navbar-item" href="{% url 'blog:articles' %}">#}
{#                                文章#}
{#                            </a>#}
{#                            <a class="navbar-item" href="{% url 'blog:about' %}">#}
{#                                关于#}
{#                            </a>#}
{#                        </div>#}

                        <!-- right side -->
                        <div class="navbar-end">
                            <div class="navbar-item">
                                <div class="field is-grouped">
                                    <p class="control">
                                        {% if not user.is_authenticated %}
                                            <a class="button is-small is-light is-rounded"
                                               href="{% url 'userprofile:login' %}">
                                                <span class="icon"><i class="fa fa-user"></i></span>
                                                <span>登录</span>
                                            </a>
                                        {% else %}
                                            <div class="dropdown is-hoverable">
                                                <div class="dropdown-trigger">
                                                    <button class="button is-rounded is-black" aria-haspopup="true"
                                                            aria-controls="dropdown-menu">
                                                        <span>{{ user.username }}</span>
                                                        <span class="icon is-small">
                                                            <i class="fas fa-angle-down" aria-hidden="true"></i>
                                                        </span>
                                                    </button>
                                                </div>
                                                <div class="dropdown-menu" id="dropdown-menu" role="menu">
                                                    <div class="dropdown-content">
                                                        <a href="{% url 'blog:article_create' %}" class="dropdown-item">
                                                            创建文章
                                                        </a>
                                                        <a href="{% url 'userprofile:logout' %}" class="dropdown-item">
                                                            退出登录
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                        {% endif %}
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </nav>
        </div>

        <!-- hero body -->
        <div class="hero-body">
            <div class="container content has-text-centered">
                <h1 class="title is-size-1 is-spaced has-text-white-bis">
                    JovyChat
                </h1>
                <h2 class="subtitle has-text-white-bis">
                    Jovy 的驻留地
                </h2>
                <p class="subtitle has-text-centered">
                    <a href="{% url 'blog:about' %}" class="button is-medium is-black is-rounded">关于我</a>
                    <a href="{% url 'blog:articles' %}" class="button is-medium is-black is-rounded">博文</a>
                    <a href="#" class="button is-medium is-black is-rounded">照片墙</a>
                </p>
            </div>
        </div>
        <!-- end hero body -->

        <!-- hero footer -->
        {#        <div class="hero-foot">#}
        {#            <nav class="tabs is-centered">#}
        {#                <div class="container">#}
        {#                    <ul>#}
        {#                        <li class="is-active"><a>概览</a></li>#}
        {#                        <li><a>介绍</a></li>#}
        {#                        <li><a>技能树</a></li>#}
        {#                    </ul>#}
        {#                </div>#}
        {#            </nav>#}
        {#        </div>#}
        <!-- end hero footer -->

    </section>

</header>

templates/blog/home.html
{% extends 'blog/base.html' %}

{% block header %}
    <section class="hero is-black is-fullheight">
        <div class="hero-body">
            <div class="container has-text-centered">
                <p class="title is-spaced is-size-1">
                    JovyChat
                </p>
                <p class="subtitle">
                    Jovy的驻留地.
                </p>
                <br>
                <p class="subtitle has-text-centered">
                    <a href="{% url 'blog:about' %}" class="button is-medium is-black is-rounded">关于我</a>
                    <a href="{% url 'blog:articles' %}" class="button is-medium is-black is-rounded">博文</a>
                    <a href="#" class="button is-medium is-black is-rounded">照片墙</a>
                </p>
            </div>
        </div>
    </section>
{% endblock %}

{% block content %}

    <!-- animation test -->

    <!-- animation end -->

    <section class="section is-medium">
        <div class="container">
            <h1 class="title has-text-centered">Section1</h1>
            <h2 class="subtitle has-text-centered">
                A simple container to divide your page into <strong>sections</strong>, like the one you're currently
                reading
            </h2>
        </div>
    </section>

    <section class="section is-large">
        <div class="container">
            <h1 class="title has-text-centered">Section2</h1>
            <h2 class="subtitle has-text-centered">
                A simple container to divide your page into <strong>sections</strong>, like the one you're currently
                reading
            </h2>
        </div>
    </section>

    <section class="section is-large">
        <div class="container">
            <h1 class="title has-text-centered">Section3</h1>
            <h2 class="subtitle has-text-centered">
                A simple container to divide your page into <strong>sections</strong>, like the one you're currently
                reading
            </h2>
        </div>
    </section>
{% endblock %}

templates/blog/resume.html
{% extends 'blog/base.html' %}
{% block content %}
{% endblock %}